//PortA IN
#define GPIOA_ODR.B0    _buttonSTOP
#define GPIOA_ODR.B1    _buttonM1
#define GPIOA_ODR.B2    _buttonM2
#define GPIOA_ODR.B3    _buttonM3
#define GPIOA_ODR.B4    _buttonM4
#define GPIOA_ODR.B5    _buttonM5
#define GPIOA_ODR.B6    _buttonM6
#define GPIOA_ODR.B7    _buttonM7
#define GPIOA_ODR.B15   _buttonM8
//Port B IN
#define GPIOB_ODR.B0    _buttonM9F
#define GPIOB_ODR.B1    _buttonM9R
#define GPIOB_ODR.B2    _buttonM10M11M12
#define GPIOB_ODR.B3    _sUMM3
#define GPIOB_ODR.B4    _sUMM5
#define GPIOB_ODR.B5    _sUMM6
#define GPIOB_ODR.B6    _sUMM7
#define GPIOB_ODR.B7    _sUMM8
#define GPIOB_ODR.B8    _sUMM9F
#define GPIOB_ODR.B9    _sUMM9R
#define GPIOB_ODR.B10   _silosL1
#define GPIOB_ODR.B11   _silosL2
#define GPIOB_ODR.B12   _silosL3
#define GPIOB_ODR.B13   _silosL4
#define GPIOB_ODR.B14   _silosL5
#define GPIOB_ODR.B15   _boilerLLOW
//Port C IN
#define GPIOC_ODR.B0    _boilerLHIGH
#define GPIOC_ODR.B1    _pilletLLOW
#define GPIOC_ODR.B2    _pilletLHIGH
#define GPIOC_ODR.B3    _thermalM1
#define GPIOC_ODR.B4    _thermalM2
#define GPIOC_ODR.B5    _thermalM3
#define GPIOC_ODR.B6    _thermalM4
#define GPIOC_ODR.B7    _thermalM5
#define GPIOC_ODR.B8    _thermalM6
#define GPIOC_ODR.B9    _thermalM7
#define GPIOC_ODR.B10   _thermalM8
#define GPIOC_ODR.B11   _thermalM9
#define GPIOC_ODR.B12   _thermalM10
#define GPIOC_ODR.B13   _thermalM11
#define GPIOC_ODR.B14   _thermalM12
#define GPIOC_ODR.B15   _vibratorSignal
//Port D IN
#define GPIOD_ODR.B0    _gotvaldSignalSwtchM1
#define GPIOD_ODR.B1    _gotvaldSignalDoor
#define GPIOD_ODR.B2    _autoBoilerBasic
#define GPIOD_ODR.B3    _autoBoilerReserv
#define GPIOD_ODR.B4    _autoPilletBasic
#define GPIOD_ODR.B5    _autoPilletReserv
//Port D OUT
#define GPIOD_ODR.B6    _lampSTOP
#define GPIOD_ODR.B7    _playM1
#define GPIOD_ODR.B8    _playM2
#define GPIOD_ODR.B9    _playM3
#define GPIOD_ODR.B10   _playM4
#define GPIOD_ODR.B11   _playM5
#define GPIOD_ODR.B12   _playM6
#define GPIOD_ODR.B13   _playM7
#define GPIOD_ODR.B14   _playM8
#define GPIOD_ODR.B15   _playM9F
//Port E OUT
#define GPIOE_ODR.B0    _playM9R
#define GPIOE_ODR.B1    _playM10
#define GPIOE_ODR.B2    _playM11
#define GPIOE_ODR.B3    _playM12
#define GPIOE_ODR.B4    _lampM1
#define GPIOE_ODR.B5    _lampM2
#define GPIOE_ODR.B6    _lampM3
#define GPIOE_ODR.B7    _lampM4
#define GPIOE_ODR.B8    _lampM5
#define GPIOE_ODR.B9    _lampM6
#define GPIOE_ODR.B10   _lampM7
#define GPIOE_ODR.B11   _lampM8
#define GPIOE_ODR.B12   _lampM9
#define GPIOE_ODR.B13   _lampM10
#define GPIOE_ODR.B14   _lampM11
#define GPIOE_ODR.B15   _lampM12